
package ws.statistics.definitions;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "statisticsws", targetNamespace = "http://statistics.ws/definitions")
@XmlSeeAlso({
    ws.statistics.definitions.ObjectFactory.class,
    ws.statistics.schemas.ObjectFactory.class
})
public interface Statisticsws {


    /**
     * Computes the average or expected value of the probability distribution corresponding to the indicated sample space. 
     * 
     * @param spaceid
     * @return
     *     returns ws.statistics.definitions.IndicatorValue
     */
    @WebMethod(action = "http://statistics.ws/definitions/calculateAverage")
    @WebResult(name = "indicatorResponse", targetNamespace = "http://statistics.ws/definitions", partName = "indicatorValue")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public IndicatorValue calculateAverage(
        @WebParam(name = "getAverage", targetNamespace = "http://statistics.ws/definitions", partName = "spaceid")
        SpaceNumber spaceid);

    /**
     * Calculates the distribution's variablity
     * 
     * @param spaceNumber
     * @return
     *     returns ws.statistics.definitions.IndicatorValue
     */
    @WebMethod(action = "http://statistics.ws/definitions/calculateDeviation")
    @WebResult(name = "indicatorResponse", targetNamespace = "http://statistics.ws/definitions", partName = "indicatorValue")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public IndicatorValue calculateDeviation(
        @WebParam(name = "getDeviation", targetNamespace = "http://statistics.ws/definitions", partName = "spaceNumber")
        SpaceNumber spaceNumber);

    /**
     * Stores a value in the muestral spaces.The operation follows the one-way pattern.
     * 									    		
     * 
     * @param value
     * @param spaceId
     */
    @WebMethod(action = "http://statistics.ws/definitions/addSample")
    @Oneway
    @RequestWrapper(localName = "addSample", targetNamespace = "http://statistics.ws/definitions", className = "ws.statistics.definitions.Sample")
    public void addSample(
        @WebParam(name = "value", targetNamespace = "")
        int value,
        @WebParam(name = "spaceId", targetNamespace = "")
        int spaceId);

    /**
     * Calculates the probability distribution of a sample space indicated in the input argument, 
     * 										    	that is, a sequence of samples and their overall frequency.
     * 										    	
     * 
     * @param spaceNumber
     * @return
     *     returns ws.statistics.definitions.DistributionResult
     */
    @WebMethod(action = "http://statistics.ws/definitions/calculateDistribution")
    @WebResult(name = "calculateDistributionResponse", targetNamespace = "http://statistics.ws/definitions", partName = "probabilityDistr")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public DistributionResult calculateDistribution(
        @WebParam(name = "getDistribution", targetNamespace = "http://statistics.ws/definitions", partName = "spaceNumber")
        SpaceNumber spaceNumber);

    /**
     * Creates a muetral space.Returns an space id
     * 
     * @param description
     * @return
     *     returns int
     */
    @WebMethod(action = "http://statistics.ws/definitions/createSpace")
    @WebResult(name = "spaceId", targetNamespace = "")
    @RequestWrapper(localName = "createSpace", targetNamespace = "http://statistics.ws/definitions", className = "ws.statistics.definitions.SpaceDescription")
    @ResponseWrapper(localName = "createSpaceResponse", targetNamespace = "http://statistics.ws/definitions", className = "ws.statistics.definitions.SpaceNumber")
    public int createSpace(
        @WebParam(name = "description", targetNamespace = "")
        String description);

}
