
package ws.statistics.definitions;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * 
 *   			Web Statistics Service provides calculations of statistical indicators such as mean, deviation, sample distribution. It also allows 
 *    			creates and muestral spaces maangement.
 * 			
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "statisticsws", targetNamespace = "http://statistics.ws/definitions", wsdlLocation = "http://localhost:8080/statisticsws/services/statisticsws?wsdl")
public class Statisticsws_Service
    extends Service
{

    private final static URL STATISTICSWS_WSDL_LOCATION;
    private final static WebServiceException STATISTICSWS_EXCEPTION;
    private final static QName STATISTICSWS_QNAME = new QName("http://statistics.ws/definitions", "statisticsws");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/statisticsws/services/statisticsws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STATISTICSWS_WSDL_LOCATION = url;
        STATISTICSWS_EXCEPTION = e;
    }

    public Statisticsws_Service() {
        super(__getWsdlLocation(), STATISTICSWS_QNAME);
    }

    public Statisticsws_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), STATISTICSWS_QNAME, features);
    }

    public Statisticsws_Service(URL wsdlLocation) {
        super(wsdlLocation, STATISTICSWS_QNAME);
    }

    public Statisticsws_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STATISTICSWS_QNAME, features);
    }

    public Statisticsws_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Statisticsws_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Statisticsws
     */
    @WebEndpoint(name = "statisticsws")
    public Statisticsws getStatisticsws() {
        return super.getPort(new QName("http://statistics.ws/definitions", "statisticsws"), Statisticsws.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Statisticsws
     */
    @WebEndpoint(name = "statisticsws")
    public Statisticsws getStatisticsws(WebServiceFeature... features) {
        return super.getPort(new QName("http://statistics.ws/definitions", "statisticsws"), Statisticsws.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STATISTICSWS_EXCEPTION!= null) {
            throw STATISTICSWS_EXCEPTION;
        }
        return STATISTICSWS_WSDL_LOCATION;
    }

}
