
package ws.taitum.definitions;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import ws.taitum.schemas.Ad;
import ws.taitum.schemas.AdType;
import ws.taitum.schemas.Ads;
import ws.taitum.schemas.Report;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "taitumws", targetNamespace = "http://taitum.ws/definitions")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ws.taitum.definitions.ObjectFactory.class,
    ws.taitum.schemas.ObjectFactory.class
})
public interface Taitumws {


    /**
     * Upload to server an ad for search or sale. When that ad matches, the server sent an email to the interested
     * 
     * @param ad
     * @param adType
     */
    @WebMethod(action = "http://taitum.ws/definitions/publish")
    @Oneway
    public void publish(
        @WebParam(name = "ad", partName = "ad")
        Ad ad,
        @WebParam(name = "adType", partName = "adType")
        AdType adType);

    /**
     * Search for and retrieve ads that match criteria. ie: the lowest price of $, proximity, street or city location exact match ... The server is able to implement any combination of those criteria (are not currently available combined queries)
     * 
     * @param ad
     * @param adType
     * @return
     *     returns ws.taitum.schemas.Ads
     * @throws UnssuportedFilter
     */
    @WebMethod(action = "http://taitum.ws/definitions/search")
    @WebResult(name = "ads", partName = "ads")
    public Ads search(
        @WebParam(name = "ad", partName = "ad")
        Ad ad,
        @WebParam(name = "adType", partName = "adType")
        AdType adType)
        throws UnssuportedFilter
    ;

    /**
     * Retrieve all ads for rent or sale actually availables. 
     * 
     * @return
     *     returns ws.taitum.schemas.Ads
     */
    @WebMethod(action = "http://taitum.ws/definitions/getOffers")
    @WebResult(name = "ads", partName = "ads")
    public Ads getAds();

    /**
     * Build a statistical report on the ads that verify certain properties. This is useful for studying relationships between user preferences, location, price patterns, leads, etc..
     * 								Throws an exception when requested by invalid data filter.
     * 
     * @param ad
     * @param adType
     * @return
     *     returns ws.taitum.schemas.Report
     * @throws UnssuportedFilter
     */
    @WebMethod(action = "http://taitum.ws/definitions/getReport")
    @WebResult(name = "report", partName = "report")
    public Report getReport(
        @WebParam(name = "ad", partName = "ad")
        Ad ad,
        @WebParam(name = "adType", partName = "adType")
        AdType adType)
        throws UnssuportedFilter
    ;

}
