
package ws.taitum.definitions;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Taitum WSregisters or publishes on property searches, Both by price, area, proximity to an address, etc (using geocoding and reverse geocoding). When something of interest,its notifies by email. Also you can extract reports on the search preferences (preferred areas, prices, correlations, etc..) to draw inferences.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "taitumws", targetNamespace = "http://taitum.ws/definitions", wsdlLocation = "http://localhost:8880/taitumws/services/taitumws?wsdl")
public class Taitumws_Service
    extends Service
{

    private final static URL TAITUMWS_WSDL_LOCATION;
    private final static WebServiceException TAITUMWS_EXCEPTION;
    private final static QName TAITUMWS_QNAME = new QName("http://taitum.ws/definitions", "taitumws");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8880/taitumws/services/taitumws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TAITUMWS_WSDL_LOCATION = url;
        TAITUMWS_EXCEPTION = e;
    }

    public Taitumws_Service() {
        super(__getWsdlLocation(), TAITUMWS_QNAME);
    }

    public Taitumws_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), TAITUMWS_QNAME, features);
    }

    public Taitumws_Service(URL wsdlLocation) {
        super(wsdlLocation, TAITUMWS_QNAME);
    }

    public Taitumws_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TAITUMWS_QNAME, features);
    }

    public Taitumws_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Taitumws_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Taitumws
     */
    @WebEndpoint(name = "taitumws")
    public Taitumws getTaitumws() {
        return super.getPort(new QName("http://taitum.ws/definitions", "taitumws"), Taitumws.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Taitumws
     */
    @WebEndpoint(name = "taitumws")
    public Taitumws getTaitumws(WebServiceFeature... features) {
        return super.getPort(new QName("http://taitum.ws/definitions", "taitumws"), Taitumws.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TAITUMWS_EXCEPTION!= null) {
            throw TAITUMWS_EXCEPTION;
        }
        return TAITUMWS_WSDL_LOCATION;
    }

}
